[2022-02-28 07:29:12,248] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.create_bucket scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 07:29:12,273] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.create_bucket scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 07:29:12,274] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 07:29:12,275] {taskinstance.py:1244} INFO - Starting attempt 4 of 4
[2022-02-28 07:29:12,276] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 07:29:12,305] {taskinstance.py:1264} INFO - Executing <Task(S3CreateBucketOperator): create_bucket> on 2022-02-25 00:00:00+00:00
[2022-02-28 07:29:12,314] {standard_task_runner.py:52} INFO - Started process 14755 to run task
[2022-02-28 07:29:12,319] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_s3_connection', 'create_bucket', 'scheduled__2022-02-25T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmpp7euh__v', '--error-file', '/tmp/tmpthfwxbfs']
[2022-02-28 07:29:12,321] {standard_task_runner.py:77} INFO - Job 60: Subtask create_bucket
[2022-02-28 07:29:12,505] {logging_mixin.py:109} INFO - Running <TaskInstance: test_s3_connection.create_bucket scheduled__2022-02-25T00:00:00+00:00 [running]> on host cdd2ec182991
[2022-02-28 07:29:12,773] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_s3_connection
AIRFLOW_CTX_TASK_ID=create_bucket
AIRFLOW_CTX_EXECUTION_DATE=2022-02-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-25T00:00:00+00:00
[2022-02-28 07:29:12,815] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-02-28 07:29:16,135] {s3.py:76} INFO - Bucket with name: s3bucket-through-***-task already exists
[2022-02-28 07:29:16,185] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=test_s3_connection, task_id=create_bucket, execution_date=20220225T000000, start_date=20220228T072912, end_date=20220228T072916
[2022-02-28 07:29:16,273] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-28 07:29:16,485] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
