[2022-02-28 09:52:24,567] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.read_file_from_s3 scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 09:52:24,584] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: test_s3_connection.read_file_from_s3 scheduled__2022-02-25T00:00:00+00:00 [queued]>
[2022-02-28 09:52:24,585] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 09:52:24,587] {taskinstance.py:1244} INFO - Starting attempt 14 of 14
[2022-02-28 09:52:24,587] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-02-28 09:52:24,604] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): read_file_from_s3> on 2022-02-25 00:00:00+00:00
[2022-02-28 09:52:24,612] {standard_task_runner.py:52} INFO - Started process 23848 to run task
[2022-02-28 09:52:24,618] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'test_s3_connection', 'read_file_from_s3', 'scheduled__2022-02-25T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/tmp/tmp5sg4xiu2', '--error-file', '/tmp/tmpcfhhf0hi']
[2022-02-28 09:52:24,620] {standard_task_runner.py:77} INFO - Job 89: Subtask read_file_from_s3
[2022-02-28 09:52:24,728] {logging_mixin.py:109} INFO - Running <TaskInstance: test_s3_connection.read_file_from_s3 scheduled__2022-02-25T00:00:00+00:00 [running]> on host cdd2ec182991
[2022-02-28 09:52:24,830] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test_s3_connection
AIRFLOW_CTX_TASK_ID=read_file_from_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-02-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-25T00:00:00+00:00
[2022-02-28 09:52:24,850] {base_aws.py:194} INFO - Credentials retrieved from extra_config
[2022-02-28 09:52:26,842] {python.py:175} INFO - Done. Returned value was: None
[2022-02-28 09:52:26,865] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=test_s3_connection, task_id=read_file_from_s3, execution_date=20220225T000000, start_date=20220228T095224, end_date=20220228T095226
[2022-02-28 09:52:26,929] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-28 09:52:26,972] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
